# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat_letter',
            new_name='seat',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_num',
        ),
    ]
