# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubhub', '0002_auto_20171225_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat',
            new_name='seat_letter',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_num',
            field=models.IntegerField(default=0),
        ),
    ]
